import { ReactNode } from 'react'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Key Yu Wan - Desenvolvedor Web',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} mx-auto max-w-6xl bg-zinc-900 px-8 text-zinc-50`}
      >
        {children}
      </body>
    </html>
  )
}
